Repository canonical/canonical-design, pull requests merged in 2025-02, with the labels that each got.

#33 feat: /brand refresh and /brand/colour-palette implementation
  templates/_layouts/_navigation.html
  templates/brand/colour-palette.html
  templates/brand/index.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#36 /brand/accessibility minor fixes
  templates/brand/accessibility.html
Labels: Review: Code +1, Review: QA +1

#35 feat: /brand/font refactor
  static/js/font.js
  static/sass/_pattern-font-tester.scss
  static/sass/styles.scss
  templates/brand/font.html
Labels: Review: Code +1, Review: QA +1, Review: Design +1

#38 feat: /brand/resources refactor
  _data/icons.yaml
  _data/resources.yaml
  static/sass/_pattern-resources.scss
  static/sass/styles.scss
  templates/brand/resources.html
  templates/shared/_email-signature.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#37 WD-18647 Refactor open-design index page
  .env
  templates/_layouts/_navigation.html
  templates/open-design/canonical-projects.html
  templates/open-design/index.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1, Review: Design +1, Review: UX +1

#32 feat: Build /get-started-designers & /get-started-maintainers
  requirements.txt
  templates/_layouts/_navigation.html
  templates/open-design/get-started-designers.html
  templates/open-design/get-started-for-designers.html
  templates/open-design/get-started-for-maintainers.html
  templates/open-design/get-started-maintainers.html
  templates/open-design/shared/_make_impact.html
Labels: Review: QA +1, Review: Design +1, Review: UX +1, Review: Code +1 (with changes)
